### ISSUE TITLE
Package not found in yarn

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reason-react-native/checkbox#3]
`yarn add @reason-react-native/checkbox` not found.

**Comment by alltonp** [comment]
I hit the same problem... from the code it looks like it should work

Are there any plans to push it to yarn?

**Comment by MoOx** [comment]
You can do until it's pushed to npm (yarn just use npm server) `yarn add https://github.com/reason-react-native/checkbox` it should work!

**Comment by MoOx** [comment]
Will close when pushed on npm :)

**Comment by alltonp** [comment]
Thank you for that. 

I'm still struggling though:

`<ReactNativeCheckbox value=true />` yields:

`Invariant Violation: Element type is invalid: expected a string (for bulit-in components) or a class/function (for composite components) but got: object.`

FYI, peer dependency is set to "@react-native-community/checkbox": "0.2.0"
but the latest version is 0.4.1 (which supports iOS too).

**Comment by MoOx** [comment]
0.4 on npm!

**Comment by MoOx** [comment]
(invariant violation should be fixed btw @alltonp)
