### ISSUE TITLE
Upgrade bindings to work with 0.4.1 (which also supports iOS)

### ISSUE THREAD

**Issue by alltonp** [reason-react-native/checkbox#4]
## The problem

There is a newer version of react-native-checkbox (0.4.x) that also supports iOS

## Considered solution

I've forked the repo to get it to work with 0.4.1, which works okay for now, but would be nice if the official bindings worked with it

see: https://github.com/alltonp/checkbox

Thanks,
Paul

**Comment by MoOx** [comment]
I followed my notifications from the bottom & missed this before REDOING the work you did 😭
Anyway should be good, except for the lineWidth thing I would like you to adjust (credit is due)
